/*
The player plays a game of standard blackjack. They try to get a higher value than the dealer without going over 21.
The dealer is also trying to win. The cards are indeed randomized, so it is not a rigged game (shocking)
When the player loses, they feel anger. Since there is an ingame currency, there are stakes to the game
*/
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let bankroll=1000, wager=0, lastBet=25, shoe=[], hands=[], active=0, dealer=[], state='bet', insurance=0, sound=true;
const suits=['♠','♥','♦','♣'], ranks=['A','2','3','4','5','6','7','8','9','10','J','Q','K'];
function money(n){return '$'+n.toLocaleString('en-US',{maximumFractionDigits:2})} function val(c){return c.r==='A'?11:['J','Q','K'].includes(c.r)?10:+c.r} function pairVal(c){return val(c)}
function freshShoe(){shoe=[];for(let d=0;d<6;d++)for(const s of suits)for(const r of ranks)shoe.push({r,s});for(let i=shoe.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[shoe[i],shoe[j]]=[shoe[j],shoe[i]]}}
function draw(){if(shoe.length<52)freshShoe();return shoe.pop()} function score(cards){let total=cards.reduce((a,c)=>a+val(c),0),aces=cards.filter(c=>c.r==='A').length;while(total>21&&aces--){total-=10}return {total,soft:aces>0}} function black(hand){return hand.cards.length===2&&score(hand.cards).total===21&&!hand.split} function dealerBJ(){return score(dealer).total===21}
function card(c,hidden=false){if(hidden)return '<div class="card back"></div>';let red=c.s==='♥'||c.s==='♦';return `<div class="card ${red?'red':''}"><div>${c.r}<br><span class="suit">${c.s}</span></div><div class="middle">${c.s}</div><div class="corner2">${c.r}<br><span class="suit">${c.s}</span></div></div>`}
function render(){ $('#bankroll').textContent=money(bankroll);$('#betAmount').textContent=money(wager); let reveal=state!=='insurance'&&state!=='player'; let ds=score(dealer);$('#dealerCards').innerHTML=dealer.length?card(dealer[0])+card(dealer[1],!reveal)+ (reveal?dealer.slice(2).map(c=>card(c)).join(''):''):'';$('#dealerScore').textContent=dealer.length?(reveal?`${ds.total}${ds.soft?' soft':''}`:'?'):'';
 $('#hands').innerHTML=hands.map((h,i)=>`<div class="hand ${i===active&&state==='player'?'active':''}"><div class="hand-label">${hands.length>1?'HAND '+(i+1):'PLAYER'} <span class="hand-score">${score(h.cards).total}${score(h.cards).soft?' soft':''}</span>${h.result?` <span class="result">${h.result}</span>`:''}</div><div class="cards">${h.cards.map(c=>card(c)).join('')}</div></div>`).join('');
 $('#betControls').classList.toggle('hidden',state!=='bet');$('#playControls').classList.toggle('hidden',state!=='player');$('#insurancePanel').classList.toggle('hidden',state!=='insurance');
 let h=hands[active];$('#doubleBtn').disabled=!h||!canDouble(h);$('#splitBtn').disabled=!h||!canSplit(h);$('#surrenderBtn').disabled=!h||!canSurrender(h);
 $$('.chip').forEach(b=>b.disabled=state!=='bet'||bankroll<+b.dataset.chip); }
function msg(t){$('#message').textContent=t} function beep(freq=440){if(!sound)return;try{let a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;g.gain.setValueAtTime(.025,a.currentTime);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.06)}catch(e){}}
function addBet(n){if(state!=='bet'||bankroll<n)return;wager+=n;bankroll-=n;beep(620);render()} function deal(){if(!wager)return msg('CHOOSE A CHIP FIRST');lastBet=wager;hands=[{cards:[draw(),draw()],bet:wager,split:false,done:false}];dealer=[draw(),draw()];active=0;if(dealer[0].r==='A'){state='insurance';msg('DEALER SHOWS ACE — INSURANCE?')}else if(val(dealer[0])===10){peek()}else startPlayer();beep(380);render()}
function insuranceChoice(take){if(take&&bankroll>=wager/2){insurance=wager/2;bankroll-=insurance}else insurance=0;peek()}
function peek(){if(dealerBJ()){state='settle';msg('DEALER HAS BLACKJACK');setTimeout(settle,550)}else startPlayer();render()}
function startPlayer(){if(black(hands[0])){state='settle';msg('BLACKJACK!');setTimeout(settle,450);return}state='player';msg('YOUR MOVE')}
function canDouble(h){return state==='player'&&h.cards.length===2&&!h.done&&!h.acesLocked&&bankroll>=h.bet} function canSplit(h){return state==='player'&&hands.length<4&&h.cards.length===2&&!h.acesLocked&&pairVal(h.cards[0])===pairVal(h.cards[1])&&bankroll>=h.bet} function canSurrender(h){return state==='player'&&hands.length===1&&h.cards.length===2&&!h.split}
function hit(){let h=hands[active];h.cards.push(draw());beep(520);if(score(h.cards).total>21){h.done=true;h.result='BUST';next()}else render()}function stand(){hands[active].done=true;next()}function doubleDown(){let h=hands[active];if(!canDouble(h))return;bankroll-=h.bet;h.bet*=2;h.cards.push(draw());h.done=true;beep(300);if(score(h.cards).total>21)h.result='BUST';next()}function split(){let h=hands[active];if(!canSplit(h))return;bankroll-=h.bet;let aces=h.cards[0].r==='A';let h2={cards:[h.cards.pop(),draw()],bet:h.bet,split:true,done:aces,acesLocked:aces};h.cards.push(draw());h.split=true;h.acesLocked=aces;h.done=aces;hands.splice(active+1,0,h2);beep(700);if(aces){msg('SPLIT ACES RECEIVE ONE CARD');setTimeout(next,350)}else render()}
function surrender(){let h=hands[active];bankroll+=h.bet/2;h.done=true;h.result='SURRENDER';msg('HALF WAGER RETURNED');next()}
function next(){let i=hands.findIndex((h,idx)=>idx>active&&!h.done);if(i>=0){active=i;msg('YOUR MOVE');render();return}if(hands.some(h=>!h.done)){hands[active].done=true} dealerTurn()}
function dealerTurn(){state='dealer';render();if(hands.every(h=>score(h.cards).total>21||h.result==='SURRENDER'))return settle();let s=score(dealer);if(s.total<17||(s.total===17&&s.soft)){setTimeout(()=>{dealer.push(draw());beep(280);dealerTurn()},450)}else{setTimeout(settle,350)}}
function settle(){let d=score(dealer).total, dbj=dealerBJ();hands.forEach(h=>{let p=score(h.cards).total;if(h.result==='SURRENDER')return;if(dbj){if(black(h)){bankroll+=h.bet;h.result='PUSH'}else h.result='LOSE';return}if(black(h)){bankroll+=h.bet*2.5;h.result='BLACKJACK +'+money(h.bet*1.5)}else if(p>21){h.result='LOSE'}else if(d>21||p>d){bankroll+=h.bet*2;h.result='WIN +'+money(h.bet)}else if(p===d){bankroll+=h.bet;h.result='PUSH'}else h.result='LOSE'});if(insurance){if(dbj){bankroll+=insurance*3;msg('INSURANCE WINS 2:1')}else msg('INSURANCE LOST')}else msg(dbj?'DEALER BLACKJACK':d>21?'DEALER BUSTS':`DEALER HAS ${d}`);state='result';render();setTimeout(()=>{state='bet';wager=0;insurance=0;msg('PLACE YOUR WAGER');render()},2200)}
$('#dealBtn').onclick=deal;$('#clearBtn').onclick=()=>{bankroll+=wager;wager=0;render()};$('#rebetBtn').onclick=()=>{if(state==='bet'&&wager===0&&bankroll>=lastBet){wager=lastBet;bankroll-=wager;render()}};$$('.chip').forEach(b=>b.onclick=()=>addBet(+b.dataset.chip));$('#hitBtn').onclick=hit;$('#standBtn').onclick=stand;$('#doubleBtn').onclick=doubleDown;$('#splitBtn').onclick=split;$('#surrenderBtn').onclick=surrender;$('#insureBtn').onclick=()=>insuranceChoice(true);$('#noInsureBtn').onclick=()=>insuranceChoice(false);$('#rulesBtn').onclick=()=>$('#rulesDialog').showModal();$('#closeRules').onclick=()=>$('#rulesDialog').close();$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=sound?'♬':'×'};document.addEventListener('keydown',e=>{if(e.key==='Enter'&&state==='bet')deal();if(state==='player'){let x={h:hit,s:stand,d:doubleDown,p:split}[e.key.toLowerCase()];if(x)x()}});freshShoe();render();
